baseURL = "https://yuya373.github.io/blog/"
languageCode = "ja-jp"
title = "blog"
theme = "temple"
enableEmoji = true
hasCJKLanguage = true
publishDir = "docs"
canonifyURLs = true

[params]
  # Enables syntax highlighting
  highlight = true
  # Supports highlighting for languages not included in the original pack
  # See https://highlightjs.org/download/
  hjslangs = ["scala", "lisp"]

# Builds a list page for each category given
[taxonomies]
  tag = "tags"
  category = "categories"

[author]
  name = "Yuya Minami"
  github = "yuya373"
